<?php

namespace UniCrm\Bundle\AdminBundle\Repository;

/**
 * ORD_OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

}
