services:
  # all services in this config are now autowired
    _defaults:
      autowire: true
      public: false

    UniCrm\Bundle\AdminBundle\DataTable\:
        class: UniCrm\Bundle\AdminBundle\DataTable\UsersDataTable
        tags: [ datatable ]

    uni_crm_app.redirect_after_registration_subscriber:
        class: UniCrm\Bundle\AdminBundle\EventListener\RedirectAfterRegistrationSubscriber
        tags :
          - { name : kernel.event_subscriber}